# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-28 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250)),
                ('location_slug', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=200)),
                ('location_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(max_length=200)),
                ('location_state', models.CharField(max_length=2)),
                ('location_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('location_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location_website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
